name: demo-action

on:
  push:
    branches: main

job:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: sample-run
        run: echo Hello World
      
